"use client";

import Link from "next/link";
import { Scale, Stethoscope, ShieldAlert, AlertTriangle, ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen text-white px-4 py-16 max-w-4xl mx-auto font-sans tracking-wide">
      <div className="relative bg-[#0f1123]/60 backdrop-blur-md border border-white/10 rounded-3xl p-6 sm:p-10 shadow-2xl overflow-hidden animate-fade-in-up">
        <div className="absolute -top-20 -right-20 w-[300px] h-[300px] bg-blue-600/10 rounded-full blur-[100px] -z-10 pointer-events-none"></div>

        <div className="flex items-center gap-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center flex-none">
            <Scale className="w-5 h-5 text-purple-400" />
          </div>
          <h1 className="text-3xl font-extrabold text-purple-400">Terms of Service</h1>
        </div>
        <p className="text-gray-400 text-xs sm:text-sm mb-6">Last Updated: May 2026</p>

        <div className="space-y-4 text-sm sm:text-base text-gray-300 leading-relaxed">
          <section className="p-4 rounded-xl hover:bg-white/5 transition-colors duration-300 animate-fade-in-up">
            <h2 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
              <Stethoscope className="w-5 h-5 text-blue-400 flex-none" /> 1. Diagnostic Decision Support
            </h2>
            <p className="text-gray-400">
              MedVision AI acts purely as a clinical computer-aided screening prototype tool. The data, segmentation masks, and probability outputs generated by the platform must be reviewed by a certified medical practitioner before initiating any patient treatment pipelines.
            </p>
          </section>

          <section className="p-4 rounded-xl hover:bg-white/5 transition-colors duration-300 animate-fade-in-up" style={{ animationDelay: "80ms" }}>
            <h2 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-purple-400 flex-none" /> 2. Operational Responsibility
            </h2>
            <p className="text-gray-400">
              Users are strictly responsible for maintaining credential confidentiality. Tampering with data pipelines, spoofing MobileNetV3 guardrails, or executing load attacks on inference servers will result in account termination.
            </p>
          </section>

          <section className="p-4 rounded-xl hover:bg-white/5 transition-colors duration-300 animate-fade-in-up" style={{ animationDelay: "160ms" }}>
            <h2 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-400 flex-none" /> 3. Limitations of Liability
            </h2>
            <p className="text-gray-400">
              As an evolving research platform, MedVision AI provides metrics on an as-is basis. We are not liable for diagnostic variations occurring outside of expert medical supervision.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-white/10">
          <Link href="/">
            <button className="group px-5 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white font-bold text-sm transition-all shadow-[0_0_20px_rgba(37,99,235,0.3)] hover:shadow-[0_0_30px_rgba(168,85,247,0.5)] hover:-translate-y-1 cursor-pointer border-0 flex items-center gap-2">
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform duration-300" /> Return to Home
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}