"use client";

import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen text-white px-4 py-16 max-w-4xl mx-auto font-sans tracking-wide">
      <div className="bg-[#0f1123]/60 backdrop-blur-md border border-white/10 rounded-3xl p-6 sm:p-10 shadow-2xl">
        <h1 className="text-3xl font-extrabold text-purple-400 mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-xs sm:text-sm mb-6">Last Updated: May 2026</p>
        
        <div className="space-y-6 text-sm sm:text-base text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-2">1. Diagnostic Decision Support</h2>
            <p className="text-gray-400">
              MedVision AI acts purely as a clinical computer-aided screening prototype tool. The data, segmentation masks, and probability outputs generated by the platform must be reviewed by a certified medical practitioner before initiating any patient treatment pipelines.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-2">2. Operational Responsibility</h2>
            <p className="text-gray-400">
              Users are strictly responsible for maintaining credential confidentiality. Tampering with data pipelines, spoofing MobileNetV3 guardrails, or executing load attacks on inference servers will result in account termination.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-2">3. Limitations of Liability</h2>
            <p className="text-gray-400">
              As an evolving research platform, MedVision AI provides metrics on an as-is basis. We are not liable for diagnostic variations occurring outside of expert medical supervision.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-white/10">
          <Link href="/">
            <button className="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-sm transition-all cursor-pointer border-0">
              Return to Home
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}