"use client";

import { useEffect, useState } from "react";
import api from "@/src/lib/axios";
import { useAuthStore } from "@/src/lib/store/useAuthStore";
import ProtectedRoute from "@/src/components/ProtectedRoute";

interface RadiologistMetrics {
  totalScans: number;
  pendingReviews: number;
  confirmedScans: number;
  needsRecheck: number;
  reviewedScans: number;
}

export default function RadiologistOverview() {
  const { user } = useAuthStore();
  const [metrics, setMetrics] = useState<RadiologistMetrics | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRadiologistMetrics = async () => {
      try {
        const res = await api.get("/api/radiologist/metrics");

        if (res.data.success) {
          setMetrics(res.data.metrics);
        }
      } catch (error) {
        console.error("Failed to load radiologist statistics:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchRadiologistMetrics();
  }, []);

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center text-white">
        <span className="text-lg font-medium animate-pulse">
          Loading radiology overview...
        </span>
      </div>
    );
  }

  return (
    <ProtectedRoute>
      <div className="p-6">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white tracking-wide">
            Welcome, {user?.name || "Radiology Reviewer"}
          </h1>

          <p className="text-gray-400 mt-2 text-sm">
            Review AI-generated MRI scan results, verify model predictions, and
            add professional radiology notes for patients.
          </p>
        </div>

        {/* Analytics Grid - Radiologist Dashboard Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">
          {/* Metric Card 1: Total AI Scans */}
          <div className="bg-[#1a163a] p-6 rounded-xl border border-gray-800 shadow-xl">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Total AI Scans
              </span>
              <span className="text-blue-500 text-xl font-bold">🧠</span>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.totalScans ?? 0}
              </h3>
              <p className="text-xs text-blue-400 mt-2">
                MRI results generated by AI
              </p>
            </div>
          </div>

          {/* Metric Card 2: Pending Reviews */}
          <div className="bg-[#1a163a] p-6 rounded-xl border border-gray-800 shadow-xl border-l-4 border-l-amber-500">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Pending Reviews
              </span>
              <span className="text-amber-500 text-xl font-bold">⏳</span>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.pendingReviews ?? 0}
              </h3>
              <p className="text-xs text-amber-400 mt-2">
                Waiting for radiologist verification
              </p>
            </div>
          </div>

          {/* Metric Card 3: Confirmed Scans */}
          <div className="bg-[#1a163a] p-6 rounded-xl border border-gray-800 shadow-xl">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Confirmed Scans
              </span>
              <span className="text-emerald-500 text-xl font-bold">✓</span>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.confirmedScans ?? 0}
              </h3>
              <p className="text-xs text-emerald-400 mt-2">
                AI predictions verified as correct
              </p>
            </div>
          </div>

          {/* Metric Card 4: Needs Recheck */}
          <div className="bg-[#1a163a] p-6 rounded-xl border border-gray-800 shadow-xl">
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Needs Recheck
              </span>
              <span className="text-red-500 text-xl font-bold">!</span>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.needsRecheck ?? 0}
              </h3>
              <p className="text-xs text-red-400 mt-2">
                Incorrect, unclear, or recheck required
              </p>
            </div>
          </div>
        </div>

        {/* Professional Workflow Section */}
        <div className="bg-[#1a163a] rounded-xl border border-gray-800 shadow-xl p-6">
          <h2 className="text-xl font-bold text-white mb-3">
            Radiology Review Workflow
          </h2>

          <p className="text-gray-400 text-sm leading-6 max-w-4xl">
            Each AI-generated MRI result is first marked as pending review. The
            radiologist can review the original MRI image, AI segmentation
            output, predicted tumor class, and confidence score. After manual
            verification, the scan can be marked as confirmed, needs recheck,
            incorrect prediction, or unclear image quality. The final
            professional note will be visible to the same patient who uploaded
            the scan.
          </p>
        </div>
      </div>
    </ProtectedRoute>
  );
}