"use client";

import { useEffect, useState } from "react";
import api from "@/src/lib/axios";
import { useAuthStore } from "@/src/lib/store/useAuthStore";
import ProtectedRoute from "@/src/components/ProtectedRoute";
import { Brain, Clock, CheckCircle2, AlertTriangle, Loader2, ClipboardList } from "lucide-react";

interface RadiologistMetrics {
  totalScans: number;
  pendingReviews: number;
  confirmedScans: number;
  needsRecheck: number;
  reviewedScans: number;
}

export default function RadiologistOverview() {
  const { user } = useAuthStore();
  const [metrics, setMetrics] = useState<RadiologistMetrics | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRadiologistMetrics = async () => {
      try {
        const res = await api.get("/api/radiologist/metrics");

        if (res.data.success) {
          setMetrics(res.data.metrics);
        }
      } catch (error) {
        console.error("Failed to load radiologist statistics:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchRadiologistMetrics();
  }, []);

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center text-white gap-3">
        <Loader2 className="w-5 h-5 text-blue-400 animate-spin" />
        <span className="text-lg font-medium animate-pulse">
          Loading radiology overview...
        </span>
      </div>
    );
  }

  return (
    <ProtectedRoute>
      <div className="p-4 sm:p-6">
        <div className="mb-8 animate-fade-in-up">
          <h1 className="text-3xl font-bold text-white tracking-wide">
            Welcome,{" "}
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-purple-400 to-blue-400 animate-gradient-x">
              {user?.name || "Radiology Reviewer"}
            </span>
          </h1>

          <p className="text-gray-400 mt-2 text-sm">
            Review AI-generated MRI scan results, verify model predictions, and
            add professional radiology notes for patients.
          </p>
        </div>

        {/* Analytics Grid - Radiologist Dashboard Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">
          {/* Metric Card 1: Total AI Scans */}
          <div
            className="bg-white/5 backdrop-blur-sm p-6 rounded-2xl border border-white/10 shadow-xl hover:-translate-y-1 hover:border-blue-500/40 transition-all duration-300 animate-fade-in-up"
            style={{ animationDelay: "0ms" }}
          >
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Total AI Scans
              </span>
              <div className="w-9 h-9 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                <Brain className="w-4 h-4 text-blue-400" />
              </div>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.totalScans ?? 0}
              </h3>
              <p className="text-xs text-blue-400 mt-2">
                MRI results generated by AI
              </p>
            </div>
          </div>

          {/* Metric Card 2: Pending Reviews */}
          <div
            className="bg-white/5 backdrop-blur-sm p-6 rounded-2xl border border-white/10 shadow-xl border-l-4 border-l-amber-500 hover:-translate-y-1 hover:border-amber-500/40 transition-all duration-300 animate-fade-in-up"
            style={{ animationDelay: "80ms" }}
          >
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Pending Reviews
              </span>
              <div className="w-9 h-9 rounded-xl bg-amber-500/10 border border-amber-500/20 flex items-center justify-center">
                <Clock className="w-4 h-4 text-amber-400" />
              </div>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.pendingReviews ?? 0}
              </h3>
              <p className="text-xs text-amber-400 mt-2">
                Waiting for radiologist verification
              </p>
            </div>
          </div>

          {/* Metric Card 3: Confirmed Scans */}
          <div
            className="bg-white/5 backdrop-blur-sm p-6 rounded-2xl border border-white/10 shadow-xl hover:-translate-y-1 hover:border-emerald-500/40 transition-all duration-300 animate-fade-in-up"
            style={{ animationDelay: "160ms" }}
          >
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Confirmed Scans
              </span>
              <div className="w-9 h-9 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              </div>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.confirmedScans ?? 0}
              </h3>
              <p className="text-xs text-emerald-400 mt-2">
                AI predictions verified as correct
              </p>
            </div>
          </div>

          {/* Metric Card 4: Needs Recheck */}
          <div
            className="bg-white/5 backdrop-blur-sm p-6 rounded-2xl border border-white/10 shadow-xl hover:-translate-y-1 hover:border-red-500/40 transition-all duration-300 animate-fade-in-up"
            style={{ animationDelay: "240ms" }}
          >
            <div className="flex items-center justify-between">
              <span className="text-sm font-semibold text-gray-400 uppercase tracking-wider">
                Needs Recheck
              </span>
              <div className="w-9 h-9 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center justify-center">
                <AlertTriangle className="w-4 h-4 text-red-400" />
              </div>
            </div>

            <div className="mt-4">
              <h3 className="text-3xl font-extrabold text-white">
                {metrics?.needsRecheck ?? 0}
              </h3>
              <p className="text-xs text-red-400 mt-2">
                Incorrect, unclear, or recheck required
              </p>
            </div>
          </div>
        </div>

        {/* Professional Workflow Section */}
        <div
          className="bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 shadow-xl p-6 animate-fade-in-up"
          style={{ animationDelay: "320ms" }}
        >
          <div className="flex items-center gap-3 mb-3">
            <div className="w-9 h-9 rounded-xl bg-purple-600/20 border border-purple-500/30 flex items-center justify-center flex-none">
              <ClipboardList className="w-4 h-4 text-purple-400" />
            </div>
            <h2 className="text-xl font-bold text-white">
              Radiology Review Workflow
            </h2>
          </div>

          <p className="text-gray-400 text-sm leading-6 max-w-4xl">
            Each AI-generated MRI result is first marked as pending review. The
            radiologist can review the original MRI image, AI segmentation
            output, predicted tumor class, and confidence score. After manual
            verification, the scan can be marked as confirmed, needs recheck,
            incorrect prediction, or unclear image quality. The final
            professional note will be visible to the same patient who uploaded
            the scan.
          </p>
        </div>
      </div>
    </ProtectedRoute>
  );
}